set		nocompatible
filetype	on
filetype	plugin	on
filetype	indent	on
syntax		on
set		nobackup
set		nowrap
set		showmode
set		history=0
set		number
set		wildmenu
set		wildmode=list:longest
colorscheme	wildcharm

inoremap	" ""<left>
inoremap	' ''<left>
inoremap	( ()<left>
inoremap	{ {}<left>
inoremap	[ []<left>

set		tabstop=8
set		shiftwidth=8
set		expandtab
set 		hlsearch
