#!/bin/bash

host1=$(docker ps|grep host_beddinao-1|awk '{print $NF}')
host2=$(docker ps|grep host_beddinao-2|awk '{print $NF}')
host3=$(docker ps|grep host_beddinao-3|awk '{print $NF}')
router1=$(docker ps|grep router_beddinao-1|awk '{print $NF}')
router2=$(docker ps|grep router_beddinao-2|awk '{print $NF}')
router3=$(docker ps|grep router_beddinao-3|awk '{print $NF}')
router4=$(docker ps|grep router_beddinao-4|awk '{print $NF}')


if [[ -z $host1 || -z $host2 || -z $host3 || -z $router1 || -z $router2 || -z $router3 || -z $router4 ]]; then
	echo "start the templates!"
	exit 1
fi

echo "got:"
echo "host_beddinao-1: $host1"
echo "host_beddinao-2: $host2"
echo "host_beddinao-3: $host3"
echo "router_beddinao-1: $router1"
echo "router_beddinao-2: $router2"
echo "router_beddinao-3: $router3"
echo "router_beddinao-4: $router4"

echo -e "\ncopying scripts:"

docker cp h1-eth0-st-script $host1:/
docker cp h2-eth0-st-script $host2:/
docker cp h3-eth0-st-script $host3:/
docker cp rr-st-script $router1:/
docker cp vtep1-st-script $router2:/
docker cp vtep2-st-script $router3:/
docker cp vtep3-st-script $router4:/

echo -e "\nexecuting the scripts:"

docker exec $host1 /bin/bash /h1-eth0-st-script
docker exec $host2 /bin/bash /h2-eth0-st-script
docker exec $host3 /bin/bash /h3-eth0-st-script
docker exec $router1 /bin/bash /rr-st-script
docker exec $router2 /bin/bash /vtep1-st-script
docker exec $router3 /bin/bash /vtep2-st-script
docker exec $router4 /bin/bash /vtep3-st-script

echo -e "\nhost1 eth0:"
docker exec $host1 ifconfig eth0
echo "host2 eth0:"
docker exec $host2 ifconfig eth0
echo "host3 eth0:"
docker exec $host3 ifconfig eth0
