#!/bin/bash

ip addr add 1.1.1.1/32 dev lo
ip addr add 10.0.1.1/30 dev eth0
ip addr add 10.0.2.1/30 dev eth1
ip addr add 10.0.3.1/30 dev eth2
ip link set lo up && ip link set eth0 up && ip link set eth1 up && ip link set eth2 up


vtysh -c 'configure terminal' \
  -c 'router ospf' \
  -c 'network 1.1.1.1/32 area 0' \
  -c 'network 10.0.1.0/30 area 0' \
  -c 'network 10.0.2.0/30 area 0' \
  -c 'network 10.0.3.0/30 area 0' \
  -c 'router bgp 1' \
  -c 'bgp router-id 1.1.1.1' \
  -c 'neighbor 1.1.1.2 remote-as 1' \
  -c 'neighbor 1.1.1.2 update-source lo' \
  -c 'neighbor 1.1.1.3 remote-as 1' \
  -c 'neighbor 1.1.1.3 update-source lo' \
  -c 'neighbor 1.1.1.4 remote-as 1' \
  -c 'neighbor 1.1.1.4 update-source lo' \
  -c 'address-family l2vpn evpn' \
  -c 'neighbor 1.1.1.2 activate' \
  -c 'neighbor 1.1.1.2 route-reflector-client' \
  -c 'neighbor 1.1.1.3 activate' \
  -c 'neighbor 1.1.1.3 route-reflector-client' \
  -c 'neighbor 1.1.1.4 activate' \
  -c 'neighbor 1.1.1.4 route-reflector-client'
