#!/bin/bash

router1=$(docker ps|grep router_beddinao-1|awk '{print $NF}')
router2=$(docker ps|grep router_beddinao-2|awk '{print $NF}')
router3=$(docker ps|grep router_beddinao-3|awk '{print $NF}')
router4=$(docker ps|grep router_beddinao-4|awk '{print $NF}')


if [[ -z $router1 || -z $router2 || -z $router3 || -z $router4 ]]; then
	echo "start the templates!"
	exit 1
fi

echo -e "\ncopying scripts:"

docker cp rtx-cnf-check-script $router1:/
docker cp rtx-cnf-check-script $router2:/
docker cp rtx-cnf-check-script $router3:/
docker cp rtx-cnf-check-script $router4:/

docker exec $router1 /bin/bash /rtx-cnf-check-script "RR (router_beddinao-1)" 
docker exec $router2 /bin/bash /rtx-cnf-check-script "leaf-1 (router_beddinao-2)"
docker exec $router3 /bin/bash /rtx-cnf-check-script "leaf-2 (router_beddinao-3)"
docker exec $router4 /bin/bash /rtx-cnf-check-script "leaf-3 (router_beddinao-4)"
